version: "3.4"
services:
  tdarr-node:
    container_name: tdarr-node
    image: ghcr.io/haveagitgat/tdarr_node:latest
    restart: always
    network_mode: bridge
    ports:
      - 8265:8265 # webUI port
    environment:
      - TZ=America/Los_Angeles
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK_SET=002
      - nodeName=Node01
      - serverIP=0.0.0.0
      - serverPort=8266
      - inContainer=true
      - ffmpegVersion=7
      - nodeType=mapped
      - priority=-1
      - cronPluginUpdate=
      - apiKey=
      - maxLogSizeMB=10
      - pollInterval=2000
      - startPaused=false
      - transcodegpuWorkers=1
      - transcodecpuWorkers=2
      - healthcheckgpuWorkers=1
      - healthcheckcpuWorkers=1
      - NVIDIA_DRIVER_CAPABILITIES=all
      - NVIDIA_VISIBLE_DEVICES=all

    volumes:
      - /docker/tdarr/configs:/app/configs
      - /docker/tdarr/logs:/app/logs
      - /media:/media
      - /transcode_cache:/temp

    devices:
      - /dev/dri:/dev/dri
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: all
            capabilities: [gpu]
    volumes:
      media:
        external: true

