services:
  tdarr-node:
    container_name: tdarr-node
    image: ghcr.io/haveagitgat/tdarr_node:latest
    restart: always
    user: root
    network_mode: bridge
    ports:
      - 8265:8265 # webUI port
    environment:
      - TZ=America/Los_Angeles
      - UMASK_SET=002
      - nodeName=TdarrN01
      - serverIP=10.30.1.2
      - serverPort=8266
      - inContainer=true
      - ffmpegVersion=7
      - nodeType=mapped
      - priority=-1
      - cronPluginUpdate=
      - apiKey=
      - maxLogSizeMB=10
      - pollInterval=2000
      - startPaused=false
      - transcodegpuWorkers=1
      - transcodecpuWorkers=2
      - healthcheckgpuWorkers=1
      - healthcheckcpuWorkers=1
      - NVIDIA_DRIVER_CAPABILITIES=all
      - NVIDIA_VISIBLE_DEVICES=all

    volumes:
      - /docker/tdarr/configs:/app/configs
      - /docker/tdarr/logs:/app/logs
      - media:/media
      - /transcode_cache:/temp

volumes:
  media:
    external: true

