name: semaphore
services:
    semaphore:
        ports:
            - 3000:3000
        image: semaphoreui/semaphore:latest
        restart: always
        environment:
            SEMAPHORE_DB_DIALECT: sqlite
            SEMAPHORE_ADMIN: ADMIN
            SEMAPHORE_ADMIN_PASSWORD: CHANGEME
            SEMAPHORE_ADMIN_NAME: ADMIN
            SEMAPHORE_ADMIN_EMAIL: ADMIN@LOCALHOST
        volumes:
            - semaphore_data:/var/lib/semaphore
            - semaphore_config:/etc/semaphore
            - semaphore_tmp:/tmp/semaphore
volumes:
    semaphore_data:
    semaphore_config:
    semaphore_tmp:
